import { existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import type { CommandResult, Finding } from './cli-types.js'
import { COMPETING_CONFIG_NAMES, OXFMT_CONFIG_NAMES, OXLINT_CONFIG_NAMES } from './config-files.js'
import { PACKAGE_NAME, PACKAGE_VERSION } from './package-metadata.js'
import { runProcess } from './process.js'
import {
  detectPackageManager,
  packageManagerAddArgs,
  readPackageJson,
  type PackageJson,
  type PackageManager
} from './project.js'
import type { AgentLintEnvironment, AgentLintFramework, AgentLintTestRunner } from './types.js'

const MANAGED_FILE_MARKER = '// Generated by @apeck14/agent-lint. Edit the factory options to customize.'
const AGENT_START = '<!-- agent-lint:start -->'
const AGENT_END = '<!-- agent-lint:end -->'
const GIT_ATTRIBUTES = '* text=auto eol=lf\n'

const SCRIPT_VALUES: Record<string, string> = {
  check: 'agent-lint check',
  deadcode: 'agent-lint deadcode',
  fix: 'agent-lint fix',
  format: 'agent-lint format --write',
  'format:check': 'agent-lint format --check',
  lint: 'agent-lint lint',
  'lint:fix': 'agent-lint lint --fix'
}

function shouldTypecheck(cwd: string, packageJson: PackageJson): boolean {
  if (packageJson.scripts?.typecheck) return true
  const dependencies = allDependencies(packageJson)
  const hasConfiguration = existsSync(join(cwd, 'tsconfig.json')) || existsSync(join(cwd, 'jsconfig.json'))
  return Boolean(dependencies.typescript && hasConfiguration)
}

function desiredScripts(cwd: string, packageJson: PackageJson): Record<string, string> {
  return {
    ...SCRIPT_VALUES,
    check: `agent-lint check${shouldTypecheck(cwd, packageJson) ? ' --typecheck' : ''}`
  }
}

function allDependencies(packageJson: PackageJson): Record<string, string> {
  return {
    ...(packageJson.dependencies ?? {}),
    ...(packageJson.devDependencies ?? {}),
    ...(packageJson.peerDependencies ?? {})
  }
}

function usableTestScript(script: string | undefined): boolean {
  return Boolean(script && !/^\s*echo\s+["']?Error:\s*no test specified\b/i.test(script))
}

function detectPreset(
  cwd: string,
  packageJson: PackageJson
): {
  environment: AgentLintEnvironment
  framework: AgentLintFramework
  testRunner: AgentLintTestRunner
} {
  const dependencies = allDependencies(packageJson)
  const hasFile = (names: string[]): boolean => names.some((name) => existsSync(join(cwd, name)))
  const hasNext =
    Boolean(dependencies.next) ||
    hasFile(['next.config.js', 'next.config.mjs', 'next.config.cjs', 'next.config.ts', 'next.config.mts'])
  const hasReact = Boolean(dependencies.react || dependencies['react-dom'])
  const framework: AgentLintFramework = hasNext ? 'next' : hasReact ? 'react' : 'none'
  const hasJest =
    Boolean(dependencies.jest || dependencies['@jest/core'] || packageJson.jest) ||
    hasFile([
      'jest.config.js',
      'jest.config.mjs',
      'jest.config.cjs',
      'jest.config.ts',
      'jest.config.cts',
      'jest.config.json'
    ])
  const hasVitest =
    Boolean(dependencies.vitest) ||
    hasFile([
      'vitest.config.js',
      'vitest.config.mjs',
      'vitest.config.cjs',
      'vitest.config.ts',
      'vitest.config.mts',
      'vitest.config.cts'
    ])
  const testRunner: AgentLintTestRunner =
    hasJest && hasVitest ? 'both' : hasJest ? 'jest' : hasVitest ? 'vitest' : 'none'
  const hasBrowserTool = Boolean(
    dependencies.vite ||
    dependencies.webpack ||
    dependencies.parcel ||
    dependencies['react-scripts'] ||
    dependencies.astro ||
    dependencies.vue ||
    dependencies.svelte ||
    dependencies['@angular/core']
  )
  const environment: AgentLintEnvironment =
    framework === 'next' ? 'universal' : hasBrowserTool || existsSync(join(cwd, 'index.html')) ? 'browser' : 'node'
  return { environment, framework, testRunner }
}

function oxlintConfig(cwd: string, packageJson: PackageJson): string {
  const preset = detectPreset(cwd, packageJson)
  return `${MANAGED_FILE_MARKER}
import { createOxlintConfig } from '@apeck14/agent-lint'

export default createOxlintConfig({
  environment: '${preset.environment}',
  framework: '${preset.framework}',
  testRunner: '${preset.testRunner}'
})
`
}

function oxfmtConfig(): string {
  return `${MANAGED_FILE_MARKER}
import { createOxfmtConfig } from '@apeck14/agent-lint'

export default createOxfmtConfig()
`
}

function setManagedFile(
  cwd: string,
  name: string,
  content: string,
  dryRun: boolean,
  notes: string[],
  candidateNames: readonly string[]
): void {
  const path = join(cwd, name)
  const otherNames = candidateNames.filter((candidate) => candidate !== name && existsSync(join(cwd, candidate)))
  if (!existsSync(path) && otherNames.length > 0) {
    const alternateName = otherNames[0] ?? ''
    const alternatePath = join(cwd, alternateName)
    const current = readFileSync(alternatePath, 'utf8')
    const canMigrate = otherNames.length === 1 && current.startsWith(MANAGED_FILE_MARKER)
    if (!canMigrate) {
      notes.push(`preserved existing ${otherNames.join(', ')}; integrate ${name} manually`)
      return
    }
    notes.push(`rename managed ${alternateName} to ${name}`)
    if (dryRun) {
      return
    }
    renameSync(alternatePath, path)
  } else if (existsSync(path) && otherNames.length > 0) {
    notes.push(`preserved additional ${otherNames.join(', ')}; remove duplicate configuration manually`)
  }

  if (existsSync(path)) {
    const current = readFileSync(path, 'utf8')
    if (!current.startsWith(MANAGED_FILE_MARKER)) {
      notes.push(`preserved custom ${name}; import the factory manually`)
      return
    }
    if (current === content) return
    notes.push(`preserved customized ${name}; update factory options manually if detection changed`)
    return
  } else {
    notes.push(`create ${name}`)
  }

  if (!dryRun) writeFileSync(path, content, 'utf8')
}

function configFileNames(packageJson: PackageJson): {
  oxfmt: string
  oxlint: string
} {
  const extension = packageJson.type === 'module' ? 'ts' : 'mts'
  return {
    oxfmt: `oxfmt.config.${extension}`,
    oxlint: `oxlint.config.${extension}`
  }
}

function addScript(packageJson: PackageJson, name: string, value: string, notes: string[]): string | undefined {
  packageJson.scripts ??= {}
  if (packageJson.scripts[name] === value) return name
  if (packageJson.scripts[name] === SCRIPT_VALUES[name] && SCRIPT_VALUES[name] !== value) {
    packageJson.scripts[name] = value
    notes.push(`update package script ${name}`)
    return name
  }
  if (packageJson.scripts[name] === undefined) {
    packageJson.scripts[name] = value
    notes.push(`add package script ${name}`)
    return name
  }

  const fallback = `agent:${name}`
  if (packageJson.scripts[fallback] === value) return fallback
  if (packageJson.scripts[fallback] === undefined) {
    packageJson.scripts[fallback] = value
    notes.push(`preserve ${name}; add package script ${fallback}`)
    return fallback
  }

  notes.push(`preserved conflicting ${name} and ${fallback}; add ${value} manually`)
  return undefined
}

function scriptInvocation(
  manager: PackageManager,
  script: string | undefined,
  command: string,
  extra: string[] = []
): string {
  if (!script) {
    const runner =
      manager === 'pnpm'
        ? 'pnpm exec'
        : manager === 'yarn'
          ? 'yarn exec'
          : manager === 'bun'
            ? 'bunx'
            : 'npx --no-install'
    return `${runner} agent-lint ${command} ${extra.join(' ')}`.trim()
  }
  if (manager === 'npm') return `npm run ${script}${extra.length > 0 ? ` -- ${extra.join(' ')}` : ''}`
  return `${manager} run ${script}${extra.length > 0 ? ` ${extra.join(' ')}` : ''}`
}

function updateAgentInstructions(
  cwd: string,
  manager: PackageManager,
  scripts: Record<string, string | undefined>,
  dryRun: boolean,
  notes: string[]
): void {
  const fix = scriptInvocation(manager, scripts.fix, 'fix', ['--changed'])
  const check = scriptInvocation(manager, scripts.check, 'check')
  const deadcode = scriptInvocation(manager, scripts.deadcode, 'deadcode')
  const test = scripts.test ? scriptInvocation(manager, scripts.test, 'test') : undefined
  const testInstruction = test ? ` Run relevant tests; run \`${test}\` for broad or shared changes.` : ''
  const block = `${AGENT_START}

## Agent checks

After code edits, run \`${fix}\`; if unrelated changes exist, replace \`--changed\` with only paths you edited. Before finishing, run \`${check}\`.${testInstruction} After adding, moving, or removing modules or dependencies, run \`${deadcode}\`. Fix causes; do not weaken rules or add ignores unless explicitly requested. Prefer real code paths; mock only external, nondeterministic, or prohibitively expensive boundaries.
${AGENT_END}`
  const path = join(cwd, 'AGENTS.md')
  const current = existsSync(path) ? readFileSync(path, 'utf8') : ''
  const start = current.indexOf(AGENT_START)
  const end = current.indexOf(AGENT_END)
  let next: string

  if (start >= 0 !== end >= 0 || (start >= 0 && end < start)) {
    notes.push('preserved malformed agent-lint block in AGENTS.md; repair its markers manually')
    return
  }

  if (start >= 0 && end >= start) {
    next = `${current.slice(0, start)}${block}${current.slice(end + AGENT_END.length)}`
  } else {
    next = `${current.trimEnd()}${current.trim() ? '\n\n' : ''}${block}\n`
  }

  if (next === current) return
  notes.push(`${current ? 'update' : 'create'} AGENTS.md managed block`)
  if (!dryRun) writeFileSync(path, next, 'utf8')
}

function createClaudeImport(cwd: string, dryRun: boolean, notes: string[]): void {
  const path = join(cwd, 'CLAUDE.md')
  if (existsSync(path)) {
    if (!readFileSync(path, 'utf8').includes('@AGENTS.md'))
      notes.push('preserved CLAUDE.md; add @AGENTS.md manually if desired')
    return
  }
  notes.push('create CLAUDE.md import')
  if (!dryRun) writeFileSync(path, '@AGENTS.md\n', 'utf8')
}

function createGitAttributes(cwd: string, dryRun: boolean, notes: string[]): void {
  const path = join(cwd, '.gitattributes')
  if (existsSync(path)) return
  notes.push('create .gitattributes with LF normalization')
  if (!dryRun) writeFileSync(path, GIT_ATTRIBUTES, 'utf8')
}

function initFailure(cwd: string, message: string): CommandResult {
  const finding: Finding = {
    column: 1,
    file: join(cwd, 'package.json'),
    line: 1,
    message,
    rule: 'init/failed',
    severity: 'error',
    tool: 'init'
  }
  return { exitCode: 2, findings: [finding] }
}

export async function initialize(cwd: string, dryRun: boolean): Promise<CommandResult> {
  const notes: string[] = []
  let packageJson: PackageJson
  let manager: PackageManager

  try {
    packageJson = readPackageJson(cwd)
    manager = detectPackageManager(cwd, packageJson)
  } catch (error) {
    return initFailure(cwd, error instanceof Error ? error.message : String(error))
  }

  const originalPackage = JSON.stringify(packageJson)
  if (packageJson.devDependencies?.[PACKAGE_NAME] !== PACKAGE_VERSION) {
    notes.push(`install ${PACKAGE_NAME}@${PACKAGE_VERSION} as an exact dev dependency`)
    if (!dryRun && process.env.AGENT_LINT_SKIP_INSTALL !== '1') {
      const [command, args] = packageManagerAddArgs(manager, `${PACKAGE_NAME}@${PACKAGE_VERSION}`)
      const result = await runProcess(command, args, cwd)
      if (result.exitCode !== 0)
        return initFailure(cwd, result.stderr.trim() || result.stdout.trim() || 'Dependency installation failed')
      packageJson = readPackageJson(cwd)
    } else if (!dryRun) {
      packageJson.devDependencies ??= {}
      packageJson.devDependencies[PACKAGE_NAME] = PACKAGE_VERSION
    }
  }

  if (packageJson.devDependencies?.[PACKAGE_NAME] === PACKAGE_VERSION && packageJson.dependencies?.[PACKAGE_NAME]) {
    delete packageJson.dependencies[PACKAGE_NAME]
    if (Object.keys(packageJson.dependencies).length === 0) delete packageJson.dependencies
    notes.push(`remove ${PACKAGE_NAME} from production dependencies`)
  }

  const selectedScripts: Record<string, string | undefined> = {}
  for (const [name, value] of Object.entries(desiredScripts(cwd, packageJson))) {
    selectedScripts[name] = addScript(packageJson, name, value, notes)
  }
  if (usableTestScript(packageJson.scripts?.test)) selectedScripts.test = 'test'

  if (JSON.stringify(packageJson) !== originalPackage && !dryRun) {
    writeFileSync(join(cwd, 'package.json'), `${JSON.stringify(packageJson, null, 2)}\n`, 'utf8')
  }

  const configs = configFileNames(packageJson)
  setManagedFile(cwd, configs.oxlint, oxlintConfig(cwd, packageJson), dryRun, notes, OXLINT_CONFIG_NAMES)
  setManagedFile(cwd, configs.oxfmt, oxfmtConfig(), dryRun, notes, OXFMT_CONFIG_NAMES)
  createGitAttributes(cwd, dryRun, notes)
  updateAgentInstructions(cwd, manager, selectedScripts, dryRun, notes)
  createClaudeImport(cwd, dryRun, notes)

  const dependencies = allDependencies(packageJson)
  const competing = [
    ...Object.keys(dependencies).filter(
      (name) =>
        name === 'eslint' ||
        name === 'prettier' ||
        name.startsWith('@eslint/') ||
        name.includes('eslint-') ||
        name.includes('prettier-')
    ),
    ...COMPETING_CONFIG_NAMES.filter((name) => existsSync(join(cwd, name)))
  ]
  if (competing.length > 0) notes.push(`review competing tooling before removal: ${competing.join(', ')}`)
  if (dryRun && notes.length === 0) notes.push('init dry-run: no changes')
  if (dryRun) notes.unshift('init dry-run')

  return { exitCode: 0, findings: [], notes }
}
